// BuildbyLinMad/FrontEnd/src/Pages/Auth/Register/Register.tsx
import { useState } from 'react';
import axios from 'axios';
import './register.css';

export default function Register({ onClose, onLoginClick }) {
  const [form, setForm] = useState({
    nombre: '',
    correo: '',
    password: '',
    confirmPassword: '',
  });
  const [showConfirmPassword, setShowConfirmPassword] = useState(false);
  const [message, setMessage] = useState('');
  const [showPassword, setShowPassword] = useState(false);

  const handleChange = (e) => {
    setForm({ ...form, [e.target.name]: e.target.value });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setMessage('');
    try {
      const res = await axios.post('http://localhost:5000/api/auth/register', form);
      setMessage(res.data.message);
      setForm({ nombre: '', correo: '', password: '', confirmPassword: ''});
    } catch (err) {
      setMessage(err.response?.data?.message || 'Error al registrar');
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center modal-fondo">
      <div className="register-modal relative w-[90%] max-w-[360px] bg-grisCard bg-opacity-80 backdrop-blur-xl border border-primario/40 rounded-2xl p-6 shadow-xl text-blancoHueso">
        
        {/* Botón cerrar */}
        <button
          onClick={onClose}
          aria-label="Cerrar"
          className="absolute top-4 right-4 text-white hover:text-hover transition-colors duration-300 p-0 bg-transparent border-none outline-none"
        >
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" className="fill-current">
            <path
              fill="currentColor"
              fillRule="evenodd"
              d="M2 12C2 6.477 6.477 2 12 2s10 4.477 10 10s-4.477 10-10 10S2 17.523 2 12m7.707-3.707a1 1 0 0 0-1.414 1.414L10.586 12l-2.293 2.293a1 1 0 1 0 1.414 1.414L12 13.414l2.293 2.293a1 1 0 0 0 1.414-1.414L13.414 12l2.293-2.293a1 1 0 0 0-1.414-1.414L12 10.586z"
              clipRule="evenodd"
            />
          </svg>
        </button>

        {/* Título */}
        <h2 className="text-3xl font-extrabold text-center mb-6">
          <span className="text-white">Crear</span>{' '}
          <span className="text-primario">Cuenta</span>
        </h2>

        {/* Mensaje */}
        {message && <p className="mb-4 text-center text-sm text-acento">{message}</p>}

        {/* Formulario */}
        <form onSubmit={handleSubmit} className="space-y-4 w-full max-w-[320px] mx-auto">
          
          {/* Nombre */}
          <div className="input-wrapper relative z-0 w-full">
            <input
              type="text"
              name="nombre"
              required
              value={form.nombre}
              onChange={handleChange}
              placeholder=" "
              className="peer block w-full appearance-none border-0 border-b-2 border-acento bg-transparent py-2.5 pr-15 text-sm text-white focus:border-primario focus:outline-none focus:ring-0"
            />
            {form.nombre === '' && (
              <label
                htmlFor="nombre"
                className="absolute left-0 text-sm text-acento duration-300 transform -translate-y-5 scale-75 top-2 z-10 peer-focus:text-primario"
              >
                Nombre completo
              </label>
            )}
          </div>

          {/* Correo */}
          <div className="input-wrapper relative z-0 w-full">
              <input
                type="email"
                name="correo"
                required
                value={form.correo}
                onChange={handleChange}
                placeholder=" "
                className="peer block w-full appearance-none border-0 border-b-2 border-acento bg-transparent py-2.5 pr-15 px-0 text-sm text-white focus:border-primario focus:outline-none focus:ring-0"
              />
              {form.correo === '' && (
                <label
                  htmlFor="correo"
                  className="absolute left-0 text-sm text-acento duration-300 transform -translate-y-5 scale-75 top-2 z-10 peer-focus:text-primario"
                >
                  Correo electrónico
                </label>
              )}
              <span className="absolute right-2 top-2.5 pointer-events-none ">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="20"
                  height="20"
                  viewBox="0 0 24 24"
                  className="fill-current"
                >
                  <path d="M20 4H4c-1.1 0-1.99.9-1.99 2L2 18c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V6c0-1.1-.9-2-2-2m0 4l-8 5l-8-5V6l8 5l8-5z" />
                </svg>
              </span>
            </div>

          {/* Contraseña */}
          <div className="input-wrapper relative z-0 w-full">
              <input
                type={showPassword ? 'text' : 'password'}
                name="password"
                required
                value={form.password}
                onChange={handleChange}
                placeholder=" "
                className="peer block w-full appearance-none border-0 border-b-2 border-acento bg-transparent py-2.5 pr-15 px-0 text-sm text-white focus:border-primario focus:outline-none focus:ring-0"
              />
              {form.password === '' && (
                <label
                  htmlFor="password"
                  className="absolute left-0 text-sm text-acento duration-300 transform -translate-y-5 scale-75 top-2 z-10 peer-focus:text-primario"
                >
                  Contraseña
                </label>
              )}
              <span
                  onClick={() => setShowPassword(!showPassword)}
                  className="absolute right-2 top-2.5 text-acento peer-focus:text-primario transition-colors duration-300 cursor-pointer"
                >
                  {showPassword ? (
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="20"
                      height="20"
                      viewBox="0 0 16 16"
                      className="w-5 h-5 fill-current"
                    >
                      <g fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5">
                        <path d="M10.12 10.827l4.026 4.027a.5.5 0 0 0 .708-.708l-13-13a.5.5 0 1 0-.708.708l3.23 3.23A6 6 0 0 0 3.2 6.182a6.7 6.7 0 0 0-1.117 1.982c-.021.061-.047.145-.047.145l-.018.062s-.076.497.355.611a.5.5 0 0 0 .611-.355l.001-.003l.008-.025l.035-.109a5.7 5.7 0 0 1 .945-1.674a5 5 0 0 1 1.124-1.014L6.675 7.38a2.5 2.5 0 1 0 3.446 3.446m-3.8-6.628l.854.854Q7.564 5 8 5c2.044 0 3.286.912 4.028 1.817a5.7 5.7 0 0 1 .945 1.674q.025.073.035.109l.008.025v.003l.001.001a.5.5 0 0 0 .966-.257v-.003l-.001-.004l-.004-.013a2 2 0 0 0-.06-.187a6.7 6.7 0 0 0-1.117-1.982C11.905 5.089 10.396 4 8.002 4c-.618 0-1.177.072-1.681.199"/>
                      </g>
                    </svg>
                  ) : (
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="20"
                      height="20"
                      viewBox="0 0 24 24"
                      className="w-5 h-5 fill-current"
                    >
                      <g fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5">
                        <path d="M3 13c3.6-8 14.4-8 18 0" />
                        <path d="M12 17a3 3 0 1 1 0-6a3 3 0 0 1 0 6" />
                      </g>
                    </svg>
                  )}
                </span>
            </div>
            {/* Confirme contarsena */}
            <div className="input-wrapper relative z-0 w-full">
              <input
                type={showConfirmPassword ? 'text' : 'password'}
                name="confirmPassword"
                value={form.confirmPassword}
                onChange={handleChange}
                placeholder="Repetir contraseña"
                required
                className="peer block w-full appearance-none border-0 border-b-2 border-acento bg-transparent py-2.5 pr-15 px-0 text-sm text-white focus:border-primario focus:outline-none focus:ring-0 placeholder-transparent"
              />
              {form.confirmPassword === '' && (
                <label
                  htmlFor="confirmPassword"
                  className="absolute left-0 text-sm text-acento duration-300 transform -translate-y-5 scale-75 top-2 z-10 peer-focus:text-primario"
                >
                  Repetir contraseña
                </label>
              )}
              <span
                onClick={() => setShowConfirmPassword(!showConfirmPassword)}
                className="absolute right-2 top-2.5 text-acento cursor-pointer transition-colors duration-300 peer-focus:text-primario"
              >
                {showConfirmPassword ? (
                  // Ojo cerrado
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="20"
                    height="20"
                    viewBox="0 0 16 16"
                    className="w-5 h-5 fill-current"
                  >
                    <g fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5">
                      <path d="M10.12 10.827l4.026 4.027a.5.5 0 0 0 .708-.708l-13-13a.5.5 0 1 0-.708.708l3.23 3.23A6 6 0 0 0 3.2 6.182a6.7 6.7 0 0 0-1.117 1.982c-.021.061-.047.145-.047.145l-.018.062s-.076.497.355.611a.5.5 0 0 0 .611-.355l.001-.003l.008-.025l.035-.109a5.7 5.7 0 0 1 .945-1.674a5 5 0 0 1 1.124-1.014L6.675 7.38a2.5 2.5 0 1 0 3.446 3.446m-3.8-6.628l.854.854Q7.564 5 8 5c2.044 0 3.286.912 4.028 1.817a5.7 5.7 0 0 1 .945 1.674q.025.073.035.109l.008.025v.003l.001.001a.5.5 0 0 0 .966-.257v-.003l-.001-.004l-.004-.013a2 2 0 0 0-.06-.187a6.7 6.7 0 0 0-1.117-1.982C11.905 5.089 10.396 4 8.002 4c-.618 0-1.177.072-1.681.199"/>
                    </g>
                  </svg>
                ) : (
                  // Ojo abierto
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="20"
                    height="20"
                    viewBox="0 0 24 24"
                    className="w-5 h-5 fill-current"
                  >
                    <g fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5">
                      <path d="M3 13c3.6-8 14.4-8 18 0" />
                      <path d="M12 17a3 3 0 1 1 0-6a3 3 0 0 1 0 6" />
                    </g>
                  </svg>
                )}
              </span>
            </div>

          {/* Botón */}
          <button
            type="submit"
            className="w-full bg-primario hover:bg-hover font-bold text-white rounded-lg text-sm px-5 py-2.5 transition-all duration-200 focus:outline-none focus:ring-0 shadow-none border-none register-btn mt-4"
          >
            REGISTRARSE
          </button>
        </form>

        <p className="text-sm mt-6 text-center text-textoSecundario">
          ¿Ya tienes cuenta?{' '}
          <span
            className="underline cursor-pointer hover:text-white"
            onClick={() => {
              onClose();
              onLoginClick();
            }}
          >
            Inicia sesión
          </span>
        </p>
      </div>
    </div>
  );
}

// LinMaDMacchiato/Frontend/src/app/pages/register/register.component.ts
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { NgIf, NgClass } from '@angular/common';
import { FirebaseAuthService } from '../../Service/firebase-auth.service';
import { FirestoreService } from '../../Service/firestore.service';
import { Router } from '@angular/router';
import { fetchSignInMethodsForEmail, getAuth } from 'firebase/auth';

@Component({
  selector: 'app-register',
  standalone: true,
  imports: [FormsModule, NgIf, NgClass],
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.scss']
})
export class RegisterComponent {
  firstName = '';
  lastName = '';
  email = '';
  password = '';
  confirmPassword = '';
  phone = '';
  role = 'cliente';

  showPassword = false;
  showConfirmPassword = false;
  errorMessage = '';
  emailExists = false;
  emailValid = false;

  constructor(
    private authService: FirebaseAuthService,
    private firestoreService: FirestoreService,
    private router: Router
  ) {}

  async register() {
    this.errorMessage = '';

    if (!this.firstName || !this.lastName || !this.email || !this.password || !this.confirmPassword) {
      this.errorMessage = 'Por favor completa todos los campos obligatorios.';
      return;
    }

    if (!this.validateEmail(this.email)) {
      this.errorMessage = 'Correo electrónico no válido.';
      return;
    }

    if (this.password !== this.confirmPassword) {
      this.errorMessage = 'Las contraseñas no coinciden.';
      return;
    }

    if (this.phone && !/^\d{9}$/.test(this.phone)) {
      this.errorMessage = 'El teléfono debe tener 9 dígitos numéricos.';
      return;
    }

    try {
      const userCredential = await this.authService.register(this.email, this.password);
      const user = userCredential.user;

      const userData = {
        uid: user.uid,
        name: `${this.firstName} ${this.lastName}`,
        email: this.email,
        phone: this.phone,
        address: '',
        role: this.role,
        createdAt: new Date().toISOString()
      };

      await this.firestoreService.saveUser(userData);
      this.router.navigate(['/']);
    } catch (error) {
      console.error('❌ Error al registrar usuario:', error);
      this.errorMessage = 'Ocurrió un error al registrarse. Intenta nuevamente.';
    }
  }

  validateEmail(email: string): boolean {
    const re = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    return re.test(email);
  }

  togglePasswordVisibility(type: 'password' | 'confirm') {
    if (type === 'password') {
      this.showPassword = !this.showPassword;
    } else {
      this.showConfirmPassword = !this.showConfirmPassword;
    }
  }

  async checkEmail() {
    this.emailValid = this.validateEmail(this.email);

    if (this.emailValid) {
      const methods = await this.getSignInMethodsForEmail(this.email);
      this.emailExists = methods && methods.length > 0;
    } else {
      this.emailExists = false;
    }
  }

  private getSignInMethodsForEmail(email: string) {
    const auth = getAuth();
    return fetchSignInMethodsForEmail(auth, email);
  }
}

<!-- REGISTRO -->
<div class="flex items-center justify-center min-h-screen" style="background: linear-gradient(135deg, #9C6F48, #3A2A25);">
  <div class="bg-white p-6 rounded-2xl shadow-lg w-[460px] border border-beigeMadera">
    <h2 class="text-xl font-bold text-center text-marronTierra mb-4 uppercase">REGISTRAR</h2>
    <form (ngSubmit)="register()" class="flex flex-col gap-4">
      <div *ngIf="errorMessage" class="text-red-500 font-semibold text-sm text-center">
        {{ errorMessage }}
      </div>
      <!-- Nombre y Apellido -->
      <div class="flex gap-4">
        <div class="flex-1">
          <label for="nombre" class="font-semibold text-verdeoscuro text-sm">Nombre:</label>
          <input id="nombre" type="text" [(ngModel)]="firstName" name="firstName" required
            class="p-2 w-full border border-beigeMadera rounded-md focus:outline-none focus:ring-2 focus:ring-verdeSalvia" />
        </div>
        <div class="flex-1">
          <label for="apellido" class="font-semibold text-verdeoscuro text-sm">Apellido:</label>
          <input id="apellido" type="text" [(ngModel)]="lastName" name="lastName" required
            class="p-2 w-full border border-beigeMadera rounded-md focus:outline-none focus:ring-2 focus:ring-verdeSalvia" />
        </div>
      </div>
      <!-- Correo -->
      <div>
        <label class="mb-1.5 block text-sm font-medium text-verdeoscuro">Correo:</label>
        <div class="relative">
          <span class="absolute top-1/2 left-0 -translate-y-1/2 border-r border-beigeMadera px-3.5 py-3 text-marronTierra">
            <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path fill="#9C6F48" fill-rule="evenodd" clip-rule="evenodd"
                    d="M3.04175 7.06206V14.375C3.04175 14.6511 3.26561 14.875 3.54175 14.875H16.4584C16.7346 14.875 16.9584 14.6511 16.9584 14.375V7.06245L11.1443 11.1168C10.457 11.5961 9.54373 11.5961 8.85638 11.1168L3.04175 7.06206Z"/>
              <path fill="#9C6F48"
                    d="M16.9584 5.19262V5.20026L10.2864 9.88638C10.1145 10.0062 9.8862 10.0062 9.71437 9.88638L3.07255 5.25485C3.07394 5.125 3.11335 5.125 3.11335 5.125H16.8871C16.9564 5.15494 16.9584 5.19262 16.9584 5.19262Z"/>
            </svg>
          </span>
          <input type="email"
            [(ngModel)]="email"
            name="email"
            (blur)="checkEmail()"
            placeholder="info@gmail.com"
            [ngClass]="{
              'border-error-300 text-error-700 focus:border-error-300 focus:ring-error-500/10': emailExists,
              'border-success-300 text-success-700 focus:border-success-300 focus:ring-success-500/10': emailValid && !emailExists
            }"
            class="h-11 w-full rounded-lg border px-4 py-2.5 pl-[60px] text-sm placeholder:text-gray-500 focus:outline-none focus:ring-2 bg-white transition-colors duration-200" />
        </div>
        <p *ngIf="email && emailExists" class="text-theme-xs text-error-500 mt-1.5">
          Este correo ya está registrado.
        </p>
        <p *ngIf="email && !emailExists && emailValid" class="text-theme-xs text-success-500 mt-1.5">
          El correo está disponible.
        </p>                     
      </div>
      <!-- Telefono -->
      <div>
        <label for="phone" class="font-semibold text-verdeoscuro text-sm">Teléfono (opcional):</label>
        <input id="phone"
               type="tel"
               [(ngModel)]="phone"
               name="phone"
               pattern="[0-9]{9}" maxlength="9"
               placeholder="+56 9 1234 5678"
               class="h-11 w-full rounded-lg border border-beigeMadera bg-white px-4 py-2.5 text-sm placeholder:text-gray-500  focus:outline-none focus:ring-2 focus:ring-verdeSalvia" />
      </div>
      <!-- Contraseña -->
      <div class="mb-4">
        <label for="password" class="mb-1.5 block text-sm font-medium text-verdeoscuro">Contraseña:</label>
        <div class="relative">
          <input [type]="showPassword ? 'text' : 'password'"
                 [(ngModel)]="password"
                 name="password"
                 id="password"
                 placeholder="Ingresa tu contraseña"
                 [ngClass]="{
                   'border-success-300 text-success-700': password && confirmPassword && password === confirmPassword,
                   'border-error-500 text-error-700': confirmPassword && password !== confirmPassword
                 }"
                 class="h-11 w-full rounded-lg border bg-white px-4 py-2.5 pr-11 text-sm text-marronTierra placeholder:text-gray-500 focus:outline-none focus:ring-2 focus:ring-verdeSalvia" />
          <span (click)="togglePasswordVisibility('password')" class="absolute right-3 top-1/2 -translate-y-1/2 cursor-pointer">
            <!-- Ojo cerrado -->
            <svg *ngIf="!showPassword" xmlns="http://www.w3.org/2000/svg" class="fill-[#9C6F48]" width="20" height="20" viewBox="0 0 20 20" fill="none">
              <path fill-rule="evenodd" clip-rule="evenodd"
                    d="M10.0002 13.8619C7.23361 13.8619 4.86803 12.1372 3.92328 9.70241C4.86804 7.26761 7.23361 5.54297 10.0002 5.54297C12.7667 5.54297 15.1323 7.26762 16.0771 9.70243C15.1323 12.1372 12.7667 13.8619 10.0002 13.8619ZM10.0002 4.04297C6.48191 4.04297 3.49489 6.30917 2.4155 9.4593C2.3615 9.61687 2.3615 9.78794 2.41549 9.94552C3.49488 13.0957 6.48191 15.3619 10.0002 15.3619C13.5184 15.3619 16.5055 13.0957 17.5849 9.94555C17.6389 9.78797 17.6389 9.6169 17.5849 9.45932C16.5055 6.30919 13.5184 4.04297 10.0002 4.04297ZM9.99151 7.84413C8.96527 7.84413 8.13333 8.67606 8.13333 9.70231C8.13333 10.7286 8.96527 11.5605 9.99151 11.5605H10.0064C11.0326 11.5605 11.8646 10.7286 11.8646 9.70231C11.8646 8.67606 11.0326 7.84413 10.0064 7.84413H9.99151Z"/>
            </svg>
      
            <!-- Ojo abierto -->
            <svg *ngIf="showPassword" xmlns="http://www.w3.org/2000/svg" class="fill-[#9C6F48]" width="20" height="20" viewBox="0 0 20 20" fill="none">
              <path fill-rule="evenodd" clip-rule="evenodd"
                    d="M4.63803 3.57709C4.34513 3.2842 3.87026 3.2842 3.57737 3.57709C3.28447 3.86999 3.28447 4.34486 3.57737 4.63775L4.85323 5.91362C3.74609 6.84199 2.89363 8.06395 2.4155 9.45936C2.3615 9.61694 2.3615 9.78801 2.41549 9.94558C3.49488 13.0957 6.48191 15.3619 10.0002 15.3619C11.255 15.3619 12.4422 15.0737 13.4994 14.5598L15.3625 16.4229C15.6554 16.7158 16.1302 16.7158 16.4231 16.4229C16.716 16.13 16.716 15.6551 16.4231 15.3622L4.63803 3.57709ZM12.3608 13.4212L10.4475 11.5079C10.3061 11.5423 10.1584 11.5606 10.0064 11.5606H9.99151C8.96527 11.5606 8.13333 10.7286 8.13333 9.70237C8.13333 9.5461 8.15262 9.39434 8.18895 9.24933L5.91885 6.97923C5.03505 7.69015 4.34057 8.62704 3.92328 9.70247C4.86803 12.1373 7.23361 13.8619 10.0002 13.8619C10.8326 13.8619 11.6287 13.7058 12.3608 13.4212ZM16.0771 9.70249C15.7843 10.4569 15.3552 11.1432 14.8199 11.7311L15.8813 12.7925C16.6329 11.9813 17.2187 11.0143 17.5849 9.94561C17.6389 9.78803 17.6389 9.61696 17.5849 9.45938C16.5055 6.30925 13.5184 4.04303 10.0002 4.04303C9.13525 4.04303 8.30244 4.17999 7.52218 4.43338L8.75139 5.66259C9.1556 5.58413 9.57311 5.54303 10.0002 5.54303C12.7667 5.54303 15.1323 7.26768 16.0771 9.70249Z"/>
            </svg>
          </span>
        </div>
      </div>

      <!-- Confirmar Contraseña -->
      <div class="mb-4">
        <label for="confirmPassword" class="mb-1.5 block text-sm font-medium text-verdeoscuro">Confirmar Contraseña:</label>
        <div class="relative">
          <input [type]="showConfirmPassword ? 'text' : 'password'"
                 [(ngModel)]="confirmPassword"
                 name="confirmPassword"
                 id="confirmPassword"
                 placeholder="Repite tu contraseña"
                 [ngClass]="{
                   'border-success-300 text-success-700': password && confirmPassword && password === confirmPassword,
                   'border-error-500 text-error-700': confirmPassword && password !== confirmPassword
                 }"
                 class="h-11 w-full rounded-lg border bg-white px-4 py-2.5 pr-11 text-sm text-marronTierra placeholder:text-gray-500 focus:outline-none focus:ring-2 focus:ring-verdeSalvia" />
          <span (click)="togglePasswordVisibility('confirm')" class="absolute right-3 top-1/2 -translate-y-1/2 cursor-pointer">
            <!-- Ojo cerrado -->
            <svg *ngIf="!showConfirmPassword" xmlns="http://www.w3.org/2000/svg" class="fill-[#9C6F48]" width="20" height="20" viewBox="0 0 20 20" fill="none">
              <path fill-rule="evenodd" clip-rule="evenodd"
                    d="M10.0002 13.8619C7.23361 13.8619 4.86803 12.1372 3.92328 9.70241C4.86804 7.26761 7.23361 5.54297 10.0002 5.54297C12.7667 5.54297 15.1323 7.26762 16.0771 9.70243C15.1323 12.1372 12.7667 13.8619 10.0002 13.8619ZM10.0002 4.04297C6.48191 4.04297 3.49489 6.30917 2.4155 9.4593C2.3615 9.61687 2.3615 9.78794 2.41549 9.94552C3.49488 13.0957 6.48191 15.3619 10.0002 15.3619C13.5184 15.3619 16.5055 13.0957 17.5849 9.94555C17.6389 9.78797 17.6389 9.6169 17.5849 9.45932C16.5055 6.30919 13.5184 4.04297 10.0002 4.04297ZM9.99151 7.84413C8.96527 7.84413 8.13333 8.67606 8.13333 9.70231C8.13333 10.7286 8.96527 11.5605 9.99151 11.5605H10.0064C11.0326 11.5605 11.8646 10.7286 11.8646 9.70231C11.8646 8.67606 11.0326 7.84413 10.0064 7.84413H9.99151Z"/>
            </svg>
      
            <!-- Ojo abierto -->
            <svg *ngIf="showConfirmPassword" xmlns="http://www.w3.org/2000/svg" class="fill-[#9C6F48]" width="20" height="20" viewBox="0 0 20 20" fill="none">
              <path fill-rule="evenodd" clip-rule="evenodd"
                    d="M4.63803 3.57709C4.34513 3.2842 3.87026 3.2842 3.57737 3.57709C3.28447 3.86999 3.28447 4.34486 3.57737 4.63775L4.85323 5.91362C3.74609 6.84199 2.89363 8.06395 2.4155 9.45936C2.3615 9.61694 2.3615 9.78801 2.41549 9.94558C3.49488 13.0957 6.48191 15.3619 10.0002 15.3619C11.255 15.3619 12.4422 15.0737 13.4994 14.5598L15.3625 16.4229C15.6554 16.7158 16.1302 16.7158 16.4231 16.4229C16.716 16.13 16.716 15.6551 16.4231 15.3622L4.63803 3.57709ZM12.3608 13.4212L10.4475 11.5079C10.3061 11.5423 10.1584 11.5606 10.0064 11.5606H9.99151C8.96527 11.5606 8.13333 10.7286 8.13333 9.70237C8.13333 9.5461 8.15262 9.39434 8.18895 9.24933L5.91885 6.97923C5.03505 7.69015 4.34057 8.62704 3.92328 9.70247C4.86803 12.1373 7.23361 13.8619 10.0002 13.8619C10.8326 13.8619 11.6287 13.7058 12.3608 13.4212ZM16.0771 9.70249C15.7843 10.4569 15.3552 11.1432 14.8199 11.7311L15.8813 12.7925C16.6329 11.9813 17.2187 11.0143 17.5849 9.94561C17.6389 9.78803 17.6389 9.61696 17.5849 9.45938C16.5055 6.30925 13.5184 4.04303 10.0002 4.04303C9.13525 4.04303 8.30244 4.17999 7.52218 4.43338L8.75139 5.66259C9.1556 5.58413 9.57311 5.54303 10.0002 5.54303C12.7667 5.54303 15.1323 7.26768 16.0771 9.70249Z"/>
            </svg>
          </span>
        </div>
      </div>
      <!-- MENSAJE DE VALIDACIÓN DE CONTRASEÑA -->
      <p *ngIf="password && confirmPassword && password !== confirmPassword" class="text-theme-xs text-error-500 mt-1.5">
        Las contraseñas no coinciden.
      </p>
      <p *ngIf="password && confirmPassword && password === confirmPassword" class="text-theme-xs text-success-500 mt-1.5">
        Las contraseñas coinciden correctamente.
      </p>        
      <!-- Boton de registar -->
      <button type="submit"
        class="w-full bg-verdeSalvia text-white py-2 rounded-md hover:bg-marronTierra transition font-bold uppercase">
        REGISTRARSE
      </button>
    </form>
  </div>
</div>
