// MentaMoka/Frontend/src/app/pages/login/login.component.ts
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { FirebaseAuthService } from '../../Service/firebase-auth.service';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [FormsModule],
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent {
  email = '';
  password = '';

  constructor(
    private authService: FirebaseAuthService,
    private router: Router
  ) {}

  async login() {
    try {
      const userCredential = await this.authService.login(this.email, this.password);
      const uid = userCredential.user.uid;

      // 🔥 Asegurar que el token está actualizado antes de obtener el rol
      await userCredential.user.getIdToken(true);

      // ✅ Obtener el rol correctamente usando `await`
      const role = await this.authService.getUserRole();

      console.log("🎭 Rol detectado:", role);

      if (role === 'administrador') {
        console.log('👑 Admin detectado, redirigiendo al panel de admin');
        this.router.navigate(['/admin']);
      } else if (role === 'cliente') {
        console.log('👤 Cliente detectado, redirigiendo al home');
        this.router.navigate(['/']);
      } else {
        console.warn('⚠️ Usuario con rol desconocido, redirigiendo al home por defecto');
        this.router.navigate(['/']);
      }
    } catch (err) {
      console.error('❌ Error al iniciar sesión:', err);
    }
  }
}


<div class="flex items-center justify-center min-h-screen bg-blancoAlgodon">
    <div class="bg-white p-8 rounded-2xl shadow-lg w-96 border border-beigeMadera">
      <h2 class="text-2xl font-bold text-center text-marronTierra mb-4">Iniciar Sesión</h2>
      <form (ngSubmit)="login()" class="space-y-4">
        <div>
          <label for="email" class="block text-sm font-medium text-marronTierra">Correo:</label>
          <input type="email" id="email" [(ngModel)]="email" name="email"
                class="mt-1 w-full p-2 border border-beigeMadera rounded-md focus:outline-none focus:ring-2 focus:ring-verdeSalvia" required>
        </div>
        <div>
          <label for="password" class="block text-sm font-medium text-marronTierra">Contraseña:</label>
          <input type="password" id="password" [(ngModel)]="password" name="password"
                class="mt-1 w-full p-2 border border-beigeMadera rounded-md focus:outline-none focus:ring-2 focus:ring-verdeSalvia" required>
        </div>
        <button type="submit"
                class="w-full bg-verdeSalvia text-white py-2 rounded-md hover:bg-marronTierra transition">
          Ingresar
        </button>
      </form>
    </div>
  </div>

// BuildbyLinMad/FrontEnd/src/Pages/Auth/Login/Login.tsx
import { useState } from 'react';
import axios from 'axios';
import { useNavigate } from 'react-router-dom';

export default function Login() {
  const [form, setForm] = useState({ correo: '', password: '' });
  const [message, setMessage] = useState('');
  const navigate = useNavigate();

  const handleChange = (e) => {
    setForm({ ...form, [e.target.name]: e.target.value });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setMessage('');
  
    try {
      const res = await axios.post('http://localhost:5000/api/auth/login', form);
      const { user } = res.data;
  
      localStorage.setItem('usuario', JSON.stringify(user));
      setMessage('Login exitoso. Redirigiendo...');
      setTimeout(() => {
        navigate('/');
        window.location.reload(); // 🔄
      }, 1500);
    } catch (err) {
      setMessage(err.response?.data?.message || 'Error al iniciar sesión');
    }
  };
  

  return (
    <main className="min-h-screen flex items-center justify-center bg-[#0D0D0D] px-4">
      <div className="w-full max-w-[350px] bg-[#1A1A1A] rounded-xl shadow-xl p-6 text-[#F4F4F5]">
        <h2 className="text-2xl font-bold mb-6 text-center text-[#7F00FF]">
          Iniciar sesión
        </h2>
  
        {message && (
          <p className="mb-4 text-center text-sm text-[#C28BFF]">{message}</p>
        )}
  
        <form onSubmit={handleSubmit} className="space-y-4">
          <input
            type="email"
            name="correo"
            placeholder="Correo"
            value={form.correo}
            onChange={handleChange}
            className="block w-full bg-[#0D0D0D] border border-[#5A32A3] text-[#F4F4F5] rounded-md px-3 py-2 placeholder:text-[#C28BFF] focus:outline-none focus:ring-2 focus:ring-[#7F00FF] text-sm"
            required
          />
          <input
            type="password"
            name="password"
            placeholder="Contraseña"
            value={form.password}
            onChange={handleChange}
            className="block w-full bg-[#0D0D0D] border border-[#5A32A3] text-[#F4F4F5] rounded-md px-3 py-2 placeholder:text-[#C28BFF] focus:outline-none focus:ring-2 focus:ring-[#7F00FF] text-sm"
            required
          />
          <button
            type="submit"
            className="w-full bg-[#7F00FF] text-white py-2 rounded-md hover:bg-[#5A32A3] transition font-medium text-sm"
          >
            Iniciar sesión
          </button>
        </form>
      </div>
    </main>
  );
  
}
